# Generated by Django 6.1 on 2026-08-24 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_classroom_student_phone_alter_student_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='email',
        ),
    ]
